### PR TITLE
Issue #8: Debloat Library

### PR DESCRIPTION
**Pull request by jcar787**
Using lodash.get, lodash.last and lodash.sortby instead of the whole loadash library.
Dist files:
- iron-db.min.js - before: 75.2 kb | after: 23.6 kb
- iron-db.js - before: 545 kb | after: 113 kb

Also added webpack-dev-server as a devDependency. 
**npm run serve** should open a server and display the contents. Easier for testing.

### CODE REVIEW

**Comment by jcar787** [comment]
Fixes
https://github.com/gruns/irondb/issues/8

**Comment by guanzo** [comment]
It should be easier to use `lodash-es`, which allows for tree shaking. Not sure if if `lodash-es` would result in a smaller bundle than individual imports.

**Comment by jcar787** [comment]
Sadly is not gonna result in small bundle, it's gonna be pretty much the same as importing lodash entirely. That's why I prefer just importing the functions that were used already.

**Comment by gruns** [comment]
> It's easier to use lodash-es, which allows for tree shaking. Not sure if
> lodash-es would result in a smaller bundle than individual imports.

Turns out, `lodash-es` indeed results in a smaller bundle than both `lodash`
(duh) and `lodash.get` + `lodash.last` + `lodash.sortby`.

Results of `npm run build` with

  * `lodash`: 76986 byte iron-db.min.js
  * `lodash.get`, `lodash.last`, and `lodash.sortby`: 24161 byte iron-db.min.js
  * `lodash-es`: 23753 byte iron-db.min.js

Winner: `lodash-es`. I switched to such in 974402a.

Huge thank you for your PR and input, @jcar787 and @guanzo. Don't hesitate to
let me know if there's anything else I can do for you.

**Pull request closed without merging**
